const menu = [
    {
        id: 1,
        title: 'Naleśniki amerykańskie',
        category: 'breakfast',
        price: 15.99,
        img: './images/item-1.jpeg',
        desc: `5 naleśników amerykańskich, podane z bitą śmietaną oraz prawdziwą belgijską czekoladą `,
    },
    {
        id: 2,
        title: 'Burger wołowy',
        category: 'lunch',
        price: 24.99,
        img: './images/item-2.jpeg',
        desc: `Burger wołowy z sezonowanego udźca 250g, podany z zestawem domowych fytek oraz colesławem `,
    },
    {
        id: 3,
        title: 'Mini burger',
        category: 'appetizer',
        price: 9.99,
        img: './images/burger.jpg',
        desc: `Mini burger ze 100g sezownowanej wołowiny, podany z sosem miodowym i bułką gryczaną`,
    },
    {
        id: 4,
        title: 'MIX owocowy',
        category: 'breakfast',
        price: 18.99,
        img: './images/p3.jpeg',
        desc: `Sałatka owocowa: jabłko, banan, kiwi, melon, papaja, ananas, winogrona, liczi  `,
    },
    {
        id: 5,
        title: 'Stek wołowy',
        category: 'lunch',
        price: 34.99,
        img: './images/p2.jpeg',
        desc: `Stek wołowy 300g z argeńtyńskiej polędwicy, podany z frytkami domowymi`,
    },
    {
        id: 6,
        title: 'Deska serów',
        category: 'appetizer',
        price: 18.99,
        img: './images/cheese.jpeg',
        desc: `Sery włosie, hiszpańskie, holenderskie podane z krakersami i winogronem`,
    },
    {
        id: 7,
        title: 'Anglielskie śniadanie',
        category: 'breakfast',
        price: 12.99,
        img: './images/item-7.jpeg',
        desc: `Bajgiel maślany, podany z sadzonymi jajami, bekonem i warzywami `,
    },
    {
        id: 8,
        title: 'Ramen z tofu',
        category: 'lunch',
        price: 19.99,
        img: './images/p1.jpeg',
        desc: `Ramen z bulionem warzywny podany z wędzonym tofu `,
    },
    {
        id: 9,
        title: 'Szaszłyki z tofu',
        category: 'appetizer',
        price: 14.99,
        img: './images/p4.jpeg',
        desc: `Tofu marynowane w oleju sezamowym, wędzone na zimno`,
    },
];
export default menu;